-- Schema for the azalea chat logger (r11).
--
-- Storage shape, and why:
--   * chat_messages_raw / player_events_raw are the physical tables. Names are
--     stored once in `name_dict` and referenced by INT4, because writing
--     "Herobrine" out again on every row is most of what a chat log costs.
--   * Fixed-width columns are ordered so there is no alignment padding
--     (8,8,4,4,4,4,1,1 packs exactly).
--   * No primary key and no foreign key on the log tables. The PK btree cost
--     ~31 bytes/row for an index only the bridge cursor read, and an FK is
--     enforced by a per-row trigger on every insert.
--   * `chat_messages` / `player_events` survive as views with the old column
--     names, so readers written against the old schema keep working.
--   * Counters live in stats_daily / player_daily. The old per-row triggers
--     serialised every writer behind one row lock.
--
--   * Only the last few days live as rows. Everything older is packed by day
--     into zstd column buckets (chat_archive / events_archive), which costs
--     ~15 bytes a row against ~138 live. `archive_closed_days(keep_days)` does
--     the packing; the accessors below hide which side a row is on.
--
-- Existing databases get here via deploy/migrate-r11.sh.

CREATE TABLE IF NOT EXISTS sessions (
  id             BIGSERIAL PRIMARY KEY,
  server_host    TEXT        NOT NULL,
  server_port    INTEGER     NOT NULL DEFAULT 25565,
  -- The protocol actually spoken to the server. With ViaVersion this differs
  -- from the version the client was built against, and that distinction is the
  -- whole reason this bot can reach servers the old one could not.
  target_version TEXT,
  client         TEXT        NOT NULL DEFAULT 'azalea',
  bot_username   TEXT,
  started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at       TIMESTAMPTZ,
  end_reason     TEXT
);

CREATE INDEX IF NOT EXISTS sessions_started_idx ON sessions (started_at DESC);
CREATE INDEX IF NOT EXISTS sessions_host_idx    ON sessions (server_host);

-- Refuse to run against a pre-r8 database rather than half-applying on top of
-- one. The logger calls this file on every start.
DO $$
BEGIN
  IF (SELECT c.relkind FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
       WHERE n.nspname = 'public' AND c.relname = 'chat_messages') = 'p' THEN
    RAISE EXCEPTION 'chat_messages is still a table: this database predates r8. '
                    'Run deploy/migrate-r8.sh before starting this build.';
  END IF;
END $$;

-- Every name the logger has ever written, exactly once. Players, mobs
-- ("Zombie"), and whatever a death message named. Deliberately not `players`:
-- that table means "a real player we have seen" and drives the kill filters and
-- the unique-player count, so mob names must not land in it.
CREATE TABLE IF NOT EXISTS name_dict (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS name_dict_lower_uidx ON name_dict (lower(name));

CREATE TABLE IF NOT EXISTS players (
  uuid       UUID PRIMARY KEY,
  name       TEXT        NOT NULL,
  first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One logical player per name. Real Mojang UUIDs win over name-based UUIDs;
-- the logger deletes extras on touch. Needed so Discord "players" totals are
-- unique names, not duplicate UUID rows.
CREATE UNIQUE INDEX IF NOT EXISTS players_name_lower_uidx ON players (lower(name));
ALTER TABLE players ADD COLUMN IF NOT EXISTS chat_rank TEXT;
-- Ties a player to the dictionary so "is this name a real player" is an int
-- join instead of lower(name) = lower(name) against a text index.
ALTER TABLE players ADD COLUMN IF NOT EXISTS name_id INTEGER;
CREATE UNIQUE INDEX IF NOT EXISTS players_name_id_uidx ON players (name_id);

-- Every name a UUID has been seen under. The old schema overwrote the name in
-- place, which lost the history the moment somebody renamed.
CREATE TABLE IF NOT EXISTS player_names (
  uuid     UUID        NOT NULL,
  name     TEXT        NOT NULL,
  seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (uuid, name)
);

-- 8,8,4,4,4,4,1,1 = 34 bytes of fixed columns with zero padding. Putting an
-- int4 between two 8-byte columns would silently cost 4 bytes on every row.
CREATE TABLE IF NOT EXISTS chat_messages_raw (
  id           BIGINT      NOT NULL,
  received_at  TIMESTAMPTZ NOT NULL,
  session_id   INTEGER,
  -- name_dict ids. NULL where the line named nobody.
  sender_id    INTEGER,
  -- Who the line is *about*, for lines with no sender: joined, left, died.
  subject_id   INTEGER,
  -- Who did the killing, for deaths phrased "... by X". May be a mob, so this
  -- points at name_dict, not players.
  killer_id    INTEGER,
  -- p | s | d (player / system / disguised)
  source       "char"      NOT NULL,
  -- c | w | j | l | d | a | s | u
  kind         "char"      NOT NULL,
  -- Chat/whisper: the message body only. Advancement: trailing [title] only.
  -- Death/join/leave: ''. Server/unknown: the line. Discord rebuilds display
  -- strings from kind + names when this is empty.
  plain_text   TEXT        NOT NULL DEFAULT ''
) PARTITION BY RANGE (received_at);

-- 8,8,4,4,1,1 = 26 bytes. player_uuid is 16 bytes and would repeat on every
-- row, so it is only stored where it disagrees with the canonical players.uuid
-- for that name; NULL costs nothing beyond the null bitmap already present.
CREATE TABLE IF NOT EXISTS player_events_raw (
  id           BIGINT      NOT NULL,
  occurred_at  TIMESTAMPTZ NOT NULL,
  session_id   INTEGER,
  player_id    INTEGER     NOT NULL,
  -- j | l | s (join / leave / snapshot)
  event_type   "char"      NOT NULL,
  -- t | c | r (tablist / chat / restart-synthesised leave)
  source       "char"      NOT NULL,
  player_uuid  UUID
) PARTITION BY RANGE (occurred_at);

CREATE SEQUENCE IF NOT EXISTS chat_messages_id_seq AS bigint OWNED BY chat_messages_raw.id;
CREATE SEQUENCE IF NOT EXISTS player_events_id_seq AS bigint OWNED BY player_events_raw.id;
ALTER TABLE chat_messages_raw ALTER COLUMN id SET DEFAULT nextval('chat_messages_id_seq');
ALTER TABLE player_events_raw ALTER COLUMN id SET DEFAULT nextval('player_events_id_seq');

CREATE INDEX IF NOT EXISTS chat_received_brin ON chat_messages_raw USING brin (received_at);
CREATE INDEX IF NOT EXISTS chat_sender_idx
  ON chat_messages_raw (sender_id, received_at DESC)
  WHERE sender_id IS NOT NULL AND kind IN ('c', 'w');
-- Deaths and advancements are a small slice of the table, so a partial index on
-- the subject stays small while still answering "what happened to X".
CREATE INDEX IF NOT EXISTS chat_subject_idx
  ON chat_messages_raw (subject_id, received_at DESC)
  WHERE subject_id IS NOT NULL AND kind IN ('d', 'a');

CREATE INDEX IF NOT EXISTS events_occurred_brin ON player_events_raw USING brin (occurred_at);
CREATE INDEX IF NOT EXISTS events_player_idx
  ON player_events_raw (player_id, occurred_at DESC)
  WHERE event_type IN ('j', 'l');

-- ---------------------------------------------------------------------------
-- Partition maintenance
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION r8_make_partitions(parent text, first_month date, last_month date)
RETURNS void LANGUAGE plpgsql AS $fn$
DECLARE
  m date;
  -- Children keep the logical name (chat_messages_2026_08), not the physical
  -- one (chat_messages_raw), so the partitions the swap renamed are the same
  -- ones this function later finds already present.
  prefix text := regexp_replace(parent, '_raw$', '');
BEGIN
  m := first_month;
  WHILE m <= last_month LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
      prefix || '_' || to_char(m, 'YYYY_MM'),
      parent,
      m::timestamp AT TIME ZONE 'UTC',
      (m + interval '1 month')::timestamp AT TIME ZONE 'UTC'
    );
    m := (m + interval '1 month')::date;
  END LOOP;
END;
$fn$;

-- Monthly children so inserts never miss a partition.
CREATE OR REPLACE FUNCTION ensure_month_partitions() RETURNS void
LANGUAGE plpgsql AS $fn$
DECLARE i int; m date;
BEGIN
  FOR i IN -1..2 LOOP
    m := (date_trunc('month', timezone('UTC', now())) + (i || ' months')::interval)::date;
    PERFORM r8_make_partitions('chat_messages_raw', m, m);
    PERFORM r8_make_partitions('player_events_raw', m, m);
  END LOOP;
END;
$fn$;

SELECT ensure_month_partitions();

-- The closed-day archive is zstd-compressed, so the extension is required.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'zstd') THEN
    RAISE EXCEPTION 'the zstd extension is missing - run deploy/install-pgzstd.sh';
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Archive: closed days packed one zstd frame per column
--
-- A chat row costs ~135 bytes on disk for ~40 bytes of text, and TOAST never
-- compresses a row that small (measured: lz4 + toast_tuple_target saved 1%).
-- Packing each column of a batch into one array makes it a single varlena,
-- which zstd then compresses - 10.6x on a real month of 6b6t. Arrays rather
-- than a serialised blob so Postgres owns the encoding and it is lossless.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS chat_archive (
  bucket      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- The UTC day this bucket covers. A busy day spans several buckets.
  day         DATE        NOT NULL,
  -- Derived, so anything written against the r10 month archive still reads.
  month       DATE        NOT NULL GENERATED ALWAYS AS (date_trunc('month', day::timestamp)::date) STORED,
  n           INTEGER     NOT NULL,
  -- Bucket bounds, so a caller can skip whole buckets without decompressing.
  min_at      TIMESTAMPTZ NOT NULL,
  max_at      TIMESTAMPTZ NOT NULL,
  -- The highest source id packed here. The delete that follows a pack is
  -- bounded by this rather than by time, so a row that arrives for this day
  -- after the pack keeps a higher id and is left alone instead of vanishing.
  max_id      BIGINT      NOT NULL,
  -- Every name_dict id this bucket mentions in any role, sorted and distinct.
  -- Without it a per-player query over a year of history decompresses every
  -- bucket to find the handful that name them.
  name_ids    INTEGER[]   NOT NULL,
  ids         BYTEA       NOT NULL,
  received_at BYTEA       NOT NULL,
  session_id  BYTEA       NOT NULL,
  sender_id   BYTEA       NOT NULL,
  subject_id  BYTEA       NOT NULL,
  killer_id   BYTEA       NOT NULL,
  source      BYTEA       NOT NULL,
  kind        BYTEA       NOT NULL,
  plain_text  BYTEA       NOT NULL
);

CREATE TABLE IF NOT EXISTS events_archive (
  bucket      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day         DATE        NOT NULL,
  month       DATE        NOT NULL GENERATED ALWAYS AS (date_trunc('month', day::timestamp)::date) STORED,
  n           INTEGER     NOT NULL,
  min_at      TIMESTAMPTZ NOT NULL,
  max_at      TIMESTAMPTZ NOT NULL,
  max_id      BIGINT      NOT NULL,
  name_ids    INTEGER[]   NOT NULL,
  ids         BYTEA       NOT NULL,
  occurred_at BYTEA       NOT NULL,
  session_id  BYTEA       NOT NULL,
  player_id   BYTEA       NOT NULL,
  event_type  BYTEA       NOT NULL,
  source      BYTEA       NOT NULL,
  player_uuid BYTEA       NOT NULL
);

-- The payload is already a zstd frame; TOAST must not try to compress it again.
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT c.relname AS tbl, a.attname AS col
    FROM pg_class c
    JOIN pg_attribute a ON a.attrelid = c.oid
    JOIN pg_type t ON t.oid = a.atttypid
    WHERE c.relname IN ('chat_archive', 'events_archive')
      AND a.attnum > 0 AND NOT a.attisdropped AND t.typname = 'bytea'
  LOOP
    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET STORAGE EXTERNAL', r.tbl, r.col);
  END LOOP;
END $$;

-- An r10 database has a chat_archive without these columns, and the CREATE
-- TABLE IF NOT EXISTS above will have quietly left it alone. Check before the
-- indexes rather than after: `CREATE INDEX ... (day)` on the old table fails
-- with "column day does not exist", which says nothing about what to do.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute
     WHERE attrelid = 'chat_archive'::regclass AND attname = 'day' AND NOT attisdropped
  ) THEN
    RAISE EXCEPTION 'chat_archive predates r11 - run deploy/migrate-r11.sh before starting this build.';
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS chat_archive_time_idx    ON chat_archive   (min_at, max_at);
CREATE INDEX IF NOT EXISTS chat_archive_day_idx     ON chat_archive   (day);
CREATE INDEX IF NOT EXISTS chat_archive_month_idx   ON chat_archive   (month);
CREATE INDEX IF NOT EXISTS chat_archive_names_idx   ON chat_archive   USING gin (name_ids);
CREATE INDEX IF NOT EXISTS events_archive_time_idx  ON events_archive (min_at, max_at);
CREATE INDEX IF NOT EXISTS events_archive_day_idx   ON events_archive (day);
CREATE INDEX IF NOT EXISTS events_archive_month_idx ON events_archive (month);
CREATE INDEX IF NOT EXISTS events_archive_names_idx ON events_archive USING gin (name_ids);

-- ---------------------------------------------------------------------------
-- Unpacking
-- ---------------------------------------------------------------------------

-- unnest() over several arrays at once zips them, so a row comes back exactly
-- as it went in. Element NULLs survive; only a wholly NULL array would drop a
-- row, which is why every array column above is NOT NULL.
CREATE OR REPLACE VIEW chat_archive_rows AS
  SELECT u.* FROM chat_archive a,
    LATERAL unnest(
      convert_from(zstd_decompress(a.ids),         'UTF8')::bigint[],
      convert_from(zstd_decompress(a.received_at), 'UTF8')::timestamptz[],
      convert_from(zstd_decompress(a.session_id),  'UTF8')::int[],
      convert_from(zstd_decompress(a.sender_id),   'UTF8')::int[],
      convert_from(zstd_decompress(a.subject_id),  'UTF8')::int[],
      convert_from(zstd_decompress(a.killer_id),   'UTF8')::int[],
      convert_from(zstd_decompress(a.source),      'UTF8')::"char"[],
      convert_from(zstd_decompress(a.kind),        'UTF8')::"char"[],
      convert_from(zstd_decompress(a.plain_text),  'UTF8')::text[]
    ) AS u(id, received_at, session_id, sender_id, subject_id, killer_id,
           source, kind, plain_text);

CREATE OR REPLACE VIEW events_archive_rows AS
  SELECT u.* FROM events_archive a,
    LATERAL unnest(
      convert_from(zstd_decompress(a.ids),         'UTF8')::bigint[],
      convert_from(zstd_decompress(a.occurred_at), 'UTF8')::timestamptz[],
      convert_from(zstd_decompress(a.session_id),  'UTF8')::int[],
      convert_from(zstd_decompress(a.player_id),   'UTF8')::int[],
      convert_from(zstd_decompress(a.event_type),  'UTF8')::"char"[],
      convert_from(zstd_decompress(a.source),      'UTF8')::"char"[],
      convert_from(zstd_decompress(a.player_uuid), 'UTF8')::uuid[]
    ) AS u(id, occurred_at, session_id, player_id, event_type, source, player_uuid);

-- ---------------------------------------------------------------------------
-- Accessors: one definition of "the log between these two timestamps"
--
-- Everything that reads history goes through these rather than naming a
-- physical table, because which side of the hot window a row is on is exactly
-- the detail a caller should not have to know. The bounds test on min_at/max_at
-- is what keeps the archive half cheap: buckets outside the range are skipped
-- whole, without a decompress.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION chat_rows_between(lo timestamptz, hi timestamptz)
RETURNS TABLE (id bigint, received_at timestamptz, session_id int, sender_id int,
               subject_id int, killer_id int, source "char", kind "char", plain_text text)
LANGUAGE sql STABLE PARALLEL SAFE AS $fn$
  SELECT c.id, c.received_at, c.session_id, c.sender_id, c.subject_id,
         c.killer_id, c.source, c.kind, c.plain_text
  FROM chat_messages_raw c
  WHERE c.received_at >= lo AND c.received_at < hi
  UNION ALL
  SELECT r.id, r.received_at, r.session_id, r.sender_id, r.subject_id,
         r.killer_id, r.source, r.kind, r.plain_text
  FROM chat_archive a
  CROSS JOIN LATERAL unnest(
      convert_from(zstd_decompress(a.ids),         'UTF8')::bigint[],
      convert_from(zstd_decompress(a.received_at), 'UTF8')::timestamptz[],
      convert_from(zstd_decompress(a.session_id),  'UTF8')::int[],
      convert_from(zstd_decompress(a.sender_id),   'UTF8')::int[],
      convert_from(zstd_decompress(a.subject_id),  'UTF8')::int[],
      convert_from(zstd_decompress(a.killer_id),   'UTF8')::int[],
      convert_from(zstd_decompress(a.source),      'UTF8')::"char"[],
      convert_from(zstd_decompress(a.kind),        'UTF8')::"char"[],
      convert_from(zstd_decompress(a.plain_text),  'UTF8')::text[]
    ) AS r(id, received_at, session_id, sender_id, subject_id, killer_id,
           source, kind, plain_text)
  WHERE a.max_at >= lo AND a.min_at < hi
    AND r.received_at >= lo AND r.received_at < hi
$fn$;

CREATE OR REPLACE FUNCTION event_rows_between(lo timestamptz, hi timestamptz)
RETURNS TABLE (id bigint, occurred_at timestamptz, session_id int, player_id int,
               event_type "char", source "char", player_uuid uuid)
LANGUAGE sql STABLE PARALLEL SAFE AS $fn$
  SELECT e.id, e.occurred_at, e.session_id, e.player_id, e.event_type, e.source, e.player_uuid
  FROM player_events_raw e
  WHERE e.occurred_at >= lo AND e.occurred_at < hi
  UNION ALL
  SELECT r.id, r.occurred_at, r.session_id, r.player_id, r.event_type, r.source, r.player_uuid
  FROM events_archive a
  CROSS JOIN LATERAL unnest(
      convert_from(zstd_decompress(a.ids),         'UTF8')::bigint[],
      convert_from(zstd_decompress(a.occurred_at), 'UTF8')::timestamptz[],
      convert_from(zstd_decompress(a.session_id),  'UTF8')::int[],
      convert_from(zstd_decompress(a.player_id),   'UTF8')::int[],
      convert_from(zstd_decompress(a.event_type),  'UTF8')::"char"[],
      convert_from(zstd_decompress(a.source),      'UTF8')::"char"[],
      convert_from(zstd_decompress(a.player_uuid), 'UTF8')::uuid[]
    ) AS r(id, occurred_at, session_id, player_id, event_type, source, player_uuid)
  WHERE a.max_at >= lo AND a.min_at < hi
    AND r.occurred_at >= lo AND r.occurred_at < hi
$fn$;

-- Same thing, narrowed to one name_dict id. The GIN index on name_ids turns
-- "everything Herobrine was ever part of" into a scan of the few buckets that
-- actually mention them instead of the whole archive.
--
-- nid may be NULL, meaning "every name". That exists so the commands with an
-- optional player argument -- /chat, /keyword -- can be one query instead of
-- two, and still prune when a player is actually given.
CREATE OR REPLACE FUNCTION chat_rows_for_name(nid int, lo timestamptz, hi timestamptz)
RETURNS TABLE (id bigint, received_at timestamptz, session_id int, sender_id int,
               subject_id int, killer_id int, source "char", kind "char", plain_text text)
LANGUAGE sql STABLE PARALLEL SAFE AS $fn$
  SELECT c.id, c.received_at, c.session_id, c.sender_id, c.subject_id,
         c.killer_id, c.source, c.kind, c.plain_text
  FROM chat_messages_raw c
  WHERE c.received_at >= lo AND c.received_at < hi
    AND (nid IS NULL OR c.sender_id = nid OR c.subject_id = nid OR c.killer_id = nid)
  UNION ALL
  SELECT r.id, r.received_at, r.session_id, r.sender_id, r.subject_id,
         r.killer_id, r.source, r.kind, r.plain_text
  FROM chat_archive a
  CROSS JOIN LATERAL unnest(
      convert_from(zstd_decompress(a.ids),         'UTF8')::bigint[],
      convert_from(zstd_decompress(a.received_at), 'UTF8')::timestamptz[],
      convert_from(zstd_decompress(a.session_id),  'UTF8')::int[],
      convert_from(zstd_decompress(a.sender_id),   'UTF8')::int[],
      convert_from(zstd_decompress(a.subject_id),  'UTF8')::int[],
      convert_from(zstd_decompress(a.killer_id),   'UTF8')::int[],
      convert_from(zstd_decompress(a.source),      'UTF8')::"char"[],
      convert_from(zstd_decompress(a.kind),        'UTF8')::"char"[],
      convert_from(zstd_decompress(a.plain_text),  'UTF8')::text[]
    ) AS r(id, received_at, session_id, sender_id, subject_id, killer_id,
           source, kind, plain_text)
  WHERE (nid IS NULL OR a.name_ids @> ARRAY[nid])
    AND a.max_at >= lo AND a.min_at < hi
    AND r.received_at >= lo AND r.received_at < hi
    AND (nid IS NULL OR r.sender_id = nid OR r.subject_id = nid OR r.killer_id = nid)
$fn$;

CREATE OR REPLACE FUNCTION event_rows_for_name(nid int, lo timestamptz, hi timestamptz)
RETURNS TABLE (id bigint, occurred_at timestamptz, session_id int, player_id int,
               event_type "char", source "char", player_uuid uuid)
LANGUAGE sql STABLE PARALLEL SAFE AS $fn$
  SELECT e.id, e.occurred_at, e.session_id, e.player_id, e.event_type, e.source, e.player_uuid
  FROM player_events_raw e
  WHERE e.occurred_at >= lo AND e.occurred_at < hi
    AND (nid IS NULL OR e.player_id = nid)
  UNION ALL
  SELECT r.id, r.occurred_at, r.session_id, r.player_id, r.event_type, r.source, r.player_uuid
  FROM events_archive a
  CROSS JOIN LATERAL unnest(
      convert_from(zstd_decompress(a.ids),         'UTF8')::bigint[],
      convert_from(zstd_decompress(a.occurred_at), 'UTF8')::timestamptz[],
      convert_from(zstd_decompress(a.session_id),  'UTF8')::int[],
      convert_from(zstd_decompress(a.player_id),   'UTF8')::int[],
      convert_from(zstd_decompress(a.event_type),  'UTF8')::"char"[],
      convert_from(zstd_decompress(a.source),      'UTF8')::"char"[],
      convert_from(zstd_decompress(a.player_uuid), 'UTF8')::uuid[]
    ) AS r(id, occurred_at, session_id, player_id, event_type, source, player_uuid)
  WHERE (nid IS NULL OR a.name_ids @> ARRAY[nid])
    AND a.max_at >= lo AND a.min_at < hi
    AND r.occurred_at >= lo AND r.occurred_at < hi
    AND (nid IS NULL OR r.player_id = nid)
$fn$;

-- ---------------------------------------------------------------------------
-- Compatibility views now span live rows and archived ones
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- Packing
--
-- A day is not a partition, so packing DELETEs its rows rather than dropping a
-- table, bounded by the highest id the pack saw. Bounding by time instead would
-- take out anything that landed between the INSERT and the DELETE.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION archive_chat_day(target_day date, batch int DEFAULT 20000)
RETURNS TABLE (packed bigint, buckets bigint, before_bytes bigint, after_bytes bigint)
LANGUAGE plpgsql AS $fn$
DECLARE
  lo timestamptz := target_day::timestamp AT TIME ZONE 'UTC';
  hi timestamptz := (target_day + 1)::timestamp AT TIME ZONE 'UTC';
  src_rows bigint; new_rows bigint; src_sum text; new_sum text;
  sz_before bigint; cap_id bigint;
BEGIN
  IF target_day >= timezone('UTC', now())::date THEN
    RAISE EXCEPTION 'refusing to archive % - that day is still being written', target_day;
  END IF;
  IF EXISTS (SELECT 1 FROM chat_archive WHERE day = target_day) THEN
    RAISE EXCEPTION 'chat_archive already holds %', target_day;
  END IF;

  -- 28 bytes is the per-row tuple header plus item pointer. Without it the
  -- "before" figure is column data alone and flatters the ratio by ~40%.
  SELECT count(*), max(id), coalesce(sum(pg_column_size(c.*)), 0) + 28 * count(*)
    INTO src_rows, cap_id, sz_before
    FROM chat_messages_raw c
   WHERE c.received_at >= lo AND c.received_at < hi;

  IF src_rows = 0 THEN
    RETURN;
  END IF;

  SELECT md5(string_agg(sig, '' ORDER BY sig)) INTO src_sum FROM (
    SELECT id::text||'|'||received_at::text||'|'||coalesce(session_id::text,'')||'|'
           ||coalesce(sender_id::text,'')||'|'||coalesce(subject_id::text,'')||'|'
           ||coalesce(killer_id::text,'')||'|'||source::text||'|'||kind::text||'|'||plain_text AS sig
    FROM chat_messages_raw
    WHERE received_at >= lo AND received_at < hi AND id <= cap_id) s;

  -- Ordering by sender first is what makes the text column compress: one
  -- player's lines sit together, and zstd's window is then full of their
  -- vocabulary rather than the whole server's.
  INSERT INTO chat_archive (day, n, min_at, max_at, max_id, name_ids, ids, received_at,
                            session_id, sender_id, subject_id, killer_id, source, kind, plain_text)
  SELECT target_day, count(*), min(received_at), max(received_at), max(id),
         (SELECT coalesce(array_agg(DISTINCT nid ORDER BY nid), '{}')
            FROM unnest(array_agg(sender_id) || array_agg(subject_id) || array_agg(killer_id)) AS t(nid)
           WHERE nid IS NOT NULL),
         zstd_compress(convert_to((array_agg(id          ORDER BY sender_id, received_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(received_at ORDER BY sender_id, received_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(session_id  ORDER BY sender_id, received_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(sender_id   ORDER BY sender_id, received_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(subject_id  ORDER BY sender_id, received_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(killer_id   ORDER BY sender_id, received_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(source      ORDER BY sender_id, received_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(kind        ORDER BY sender_id, received_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(plain_text  ORDER BY sender_id, received_at, id))::text, 'UTF8'), NULL, 19)
  FROM (
    SELECT *, (row_number() OVER (ORDER BY received_at, id) - 1) / batch AS b
    FROM chat_messages_raw
    WHERE received_at >= lo AND received_at < hi AND id <= cap_id
  ) x
  GROUP BY b;

  SELECT count(*) INTO new_rows FROM chat_archive_rows
   WHERE received_at >= lo AND received_at < hi;

  SELECT md5(string_agg(sig, '' ORDER BY sig)) INTO new_sum FROM (
    SELECT id::text||'|'||received_at::text||'|'||coalesce(session_id::text,'')||'|'
           ||coalesce(sender_id::text,'')||'|'||coalesce(subject_id::text,'')||'|'
           ||coalesce(killer_id::text,'')||'|'||source::text||'|'||kind::text||'|'||plain_text AS sig
    FROM chat_archive_rows WHERE received_at >= lo AND received_at < hi) s;

  IF new_rows <> src_rows OR new_sum IS DISTINCT FROM src_sum THEN
    DELETE FROM chat_archive WHERE day = target_day;
    RAISE EXCEPTION 'archive of % did not match the source (% vs % rows, checksum %) - nothing deleted',
      target_day, src_rows, new_rows, CASE WHEN new_sum = src_sum THEN 'ok' ELSE 'MISMATCH' END;
  END IF;

  DELETE FROM chat_messages_raw
   WHERE received_at >= lo AND received_at < hi AND id <= cap_id;

  packed := src_rows;
  before_bytes := sz_before;
  SELECT count(*), coalesce(sum(pg_column_size(a.*)), 0) INTO buckets, after_bytes
    FROM chat_archive a WHERE a.day = target_day;
  RETURN NEXT;
END;
$fn$;

CREATE OR REPLACE FUNCTION archive_events_day(target_day date, batch int DEFAULT 20000)
RETURNS TABLE (packed bigint, buckets bigint, before_bytes bigint, after_bytes bigint)
LANGUAGE plpgsql AS $fn$
DECLARE
  lo timestamptz := target_day::timestamp AT TIME ZONE 'UTC';
  hi timestamptz := (target_day + 1)::timestamp AT TIME ZONE 'UTC';
  src_rows bigint; new_rows bigint; src_sum text; new_sum text;
  sz_before bigint; cap_id bigint;
BEGIN
  IF target_day >= timezone('UTC', now())::date THEN
    RAISE EXCEPTION 'refusing to archive % - that day is still being written', target_day;
  END IF;
  IF EXISTS (SELECT 1 FROM events_archive WHERE day = target_day) THEN
    RAISE EXCEPTION 'events_archive already holds %', target_day;
  END IF;

  SELECT count(*), max(id), coalesce(sum(pg_column_size(e.*)), 0) + 28 * count(*)
    INTO src_rows, cap_id, sz_before
    FROM player_events_raw e
   WHERE e.occurred_at >= lo AND e.occurred_at < hi;

  IF src_rows = 0 THEN
    RETURN;
  END IF;

  SELECT md5(string_agg(sig, '' ORDER BY sig)) INTO src_sum FROM (
    SELECT id::text||'|'||occurred_at::text||'|'||coalesce(session_id::text,'')||'|'
           ||player_id::text||'|'||event_type::text||'|'||source::text||'|'
           ||coalesce(player_uuid::text,'') AS sig
    FROM player_events_raw
    WHERE occurred_at >= lo AND occurred_at < hi AND id <= cap_id) s;

  INSERT INTO events_archive (day, n, min_at, max_at, max_id, name_ids, ids, occurred_at,
                              session_id, player_id, event_type, source, player_uuid)
  SELECT target_day, count(*), min(occurred_at), max(occurred_at), max(id),
         (SELECT coalesce(array_agg(DISTINCT nid ORDER BY nid), '{}')
            FROM unnest(array_agg(player_id)) AS t(nid) WHERE nid IS NOT NULL),
         zstd_compress(convert_to((array_agg(id          ORDER BY player_id, occurred_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(occurred_at ORDER BY player_id, occurred_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(session_id  ORDER BY player_id, occurred_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(player_id   ORDER BY player_id, occurred_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(event_type  ORDER BY player_id, occurred_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(source      ORDER BY player_id, occurred_at, id))::text, 'UTF8'), NULL, 19),
         zstd_compress(convert_to((array_agg(player_uuid ORDER BY player_id, occurred_at, id))::text, 'UTF8'), NULL, 19)
  FROM (
    SELECT *, (row_number() OVER (ORDER BY occurred_at, id) - 1) / batch AS b
    FROM player_events_raw
    WHERE occurred_at >= lo AND occurred_at < hi AND id <= cap_id
  ) x
  GROUP BY b;

  SELECT count(*) INTO new_rows FROM events_archive_rows
   WHERE occurred_at >= lo AND occurred_at < hi;

  SELECT md5(string_agg(sig, '' ORDER BY sig)) INTO new_sum FROM (
    SELECT id::text||'|'||occurred_at::text||'|'||coalesce(session_id::text,'')||'|'
           ||player_id::text||'|'||event_type::text||'|'||source::text||'|'
           ||coalesce(player_uuid::text,'') AS sig
    FROM events_archive_rows WHERE occurred_at >= lo AND occurred_at < hi) s;

  IF new_rows <> src_rows OR new_sum IS DISTINCT FROM src_sum THEN
    DELETE FROM events_archive WHERE day = target_day;
    RAISE EXCEPTION 'archive of % did not match the source (% vs % rows, checksum %) - nothing deleted',
      target_day, src_rows, new_rows, CASE WHEN new_sum = src_sum THEN 'ok' ELSE 'MISMATCH' END;
  END IF;

  DELETE FROM player_events_raw
   WHERE occurred_at >= lo AND occurred_at < hi AND id <= cap_id;

  packed := src_rows;
  before_bytes := sz_before;
  SELECT count(*), coalesce(sum(pg_column_size(a.*)), 0) INTO buckets, after_bytes
    FROM events_archive a WHERE a.day = target_day;
  RETURN NEXT;
END;
$fn$;

-- Drop month partitions that are empty and cannot receive anything again.
-- Once every day of a month is archived its partition is an empty shell.
CREATE OR REPLACE FUNCTION drop_empty_partitions()
RETURNS TABLE (dropped text)
LANGUAGE plpgsql AS $fn$
DECLARE r record; n bigint; this_month date := date_trunc('month', timezone('UTC', now()))::date;
BEGIN
  FOR r IN
    SELECT c.relname AS part, parent.relname AS parent
    FROM pg_class c
    JOIN pg_inherits i ON i.inhrelid = c.oid
    JOIN pg_class parent ON parent.oid = i.inhparent
    WHERE parent.relname IN ('chat_messages_raw', 'player_events_raw')
    ORDER BY c.relname
  LOOP
    -- chat_messages_2026_07 -> 2026-07-01
    CONTINUE WHEN to_date(right(r.part, 7), 'YYYY_MM') >= this_month;
    EXECUTE format('SELECT count(*) FROM %I', r.part) INTO n;
    CONTINUE WHEN n > 0;
    EXECUTE format('DROP TABLE %I', r.part);
    dropped := r.part;
    RETURN NEXT;
  END LOOP;
END;
$fn$;

-- ---------------------------------------------------------------------------
-- The driver
--
-- keep_days counts calendar days in UTC *including today*, so keep_days => 7 on
-- the 19th keeps the 13th through the 19th and packs everything on or before
-- the 12th. Anything already packed is skipped, which makes this safe to run
-- from cron as often as you like.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION archive_closed_days(keep_days int DEFAULT 7, batch int DEFAULT 20000)
RETURNS TABLE (kind text, day date, packed bigint, buckets bigint,
               before_bytes bigint, after_bytes bigint)
LANGUAGE plpgsql AS $fn$
DECLARE
  cutoff date := timezone('UTC', now())::date - (keep_days - 1);
  d date;
  res record;
BEGIN
  IF keep_days < 1 THEN
    RAISE EXCEPTION 'keep_days must be at least 1 - the current day is never archivable';
  END IF;

  FOR d IN
    SELECT DISTINCT (received_at AT TIME ZONE 'UTC')::date AS dd
    FROM chat_messages_raw
    WHERE received_at < cutoff::timestamp AT TIME ZONE 'UTC'
    ORDER BY 1
  LOOP
    CONTINUE WHEN EXISTS (SELECT 1 FROM chat_archive WHERE chat_archive.day = d);
    FOR res IN SELECT * FROM archive_chat_day(d, batch) LOOP
      kind := 'chat'; day := d;
      packed := res.packed; buckets := res.buckets;
      before_bytes := res.before_bytes; after_bytes := res.after_bytes;
      RETURN NEXT;
    END LOOP;
  END LOOP;

  FOR d IN
    SELECT DISTINCT (occurred_at AT TIME ZONE 'UTC')::date AS dd
    FROM player_events_raw
    WHERE occurred_at < cutoff::timestamp AT TIME ZONE 'UTC'
    ORDER BY 1
  LOOP
    CONTINUE WHEN EXISTS (SELECT 1 FROM events_archive WHERE events_archive.day = d);
    FOR res IN SELECT * FROM archive_events_day(d, batch) LOOP
      kind := 'events'; day := d;
      packed := res.packed; buckets := res.buckets;
      before_bytes := res.before_bytes; after_bytes := res.after_bytes;
      RETURN NEXT;
    END LOOP;
  END LOOP;

  PERFORM drop_empty_partitions();
END;
$fn$;

-- Compatibility views: old column names, new storage
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW chat_messages AS
  SELECT c.id, c.session_id::bigint AS session_id, c.received_at, c.source, c.kind,
         snd.name AS sender_name, subj.name AS subject_name, kil.name AS killer_name,
         c.plain_text
  FROM chat_messages_raw c
  LEFT JOIN name_dict snd  ON snd.id  = c.sender_id
  LEFT JOIN name_dict subj ON subj.id = c.subject_id
  LEFT JOIN name_dict kil  ON kil.id  = c.killer_id
  UNION ALL
  SELECT a.id, a.session_id::bigint, a.received_at, a.source, a.kind,
         snd.name, subj.name, kil.name, a.plain_text
  FROM chat_archive_rows a
  LEFT JOIN name_dict snd  ON snd.id  = a.sender_id
  LEFT JOIN name_dict subj ON subj.id = a.subject_id
  LEFT JOIN name_dict kil  ON kil.id  = a.killer_id;

CREATE OR REPLACE VIEW player_events AS
  SELECT e.id, e.session_id::bigint AS session_id, e.occurred_at, e.event_type, e.source,
         nd.name AS player_name, COALESCE(e.player_uuid, p.uuid) AS player_uuid
  FROM player_events_raw e
  JOIN name_dict nd ON nd.id = e.player_id
  LEFT JOIN players p ON p.name_id = e.player_id
  UNION ALL
  SELECT a.id, a.session_id::bigint, a.occurred_at, a.event_type, a.source,
         nd.name, COALESCE(a.player_uuid, p.uuid)
  FROM events_archive_rows a
  JOIN name_dict nd ON nd.id = a.player_id
  LEFT JOIN players p ON p.name_id = a.player_id;

CREATE OR REPLACE VIEW recent_chat AS
  SELECT c.received_at, s.server_host, c.kind::text AS kind, nd.name AS sender_name, c.plain_text
  FROM chat_messages_raw c
  LEFT JOIN name_dict nd ON nd.id = c.sender_id
  LEFT JOIN sessions s ON s.id = c.session_id
  WHERE c.kind IN ('c', 'w')
  UNION ALL
  SELECT a.received_at, s.server_host, a.kind::text, nd.name, a.plain_text
  FROM chat_archive_rows a
  LEFT JOIN name_dict nd ON nd.id = a.sender_id
  LEFT JOIN sessions s ON s.id = a.session_id
  WHERE a.kind IN ('c', 'w')
  ORDER BY received_at DESC;

CREATE OR REPLACE VIEW player_kills AS
  SELECT c.received_at, kil.name AS killer, subj.name AS victim, s.server_host, c.plain_text
  FROM chat_messages_raw c
  JOIN name_dict kil  ON kil.id  = c.killer_id
  JOIN name_dict subj ON subj.id = c.subject_id
  JOIN players kp ON kp.name_id = c.killer_id
  LEFT JOIN sessions s ON s.id = c.session_id
  WHERE c.kind = 'd'::"char"
  UNION ALL
  SELECT a.received_at, kil.name, subj.name, s.server_host, a.plain_text
  FROM chat_archive_rows a
  JOIN name_dict kil  ON kil.id  = a.killer_id
  JOIN name_dict subj ON subj.id = a.subject_id
  JOIN players kp ON kp.name_id = a.killer_id
  LEFT JOIN sessions s ON s.id = a.session_id
  WHERE a.kind = 'd'::"char";

-- ---------------------------------------------------------------------------
-- Packing one day
-- ---------------------------------------------------------------------------

-- Buckets are cut on time order so min_at/max_at stay tight and prunable, but
-- the rows *inside* a bucket are ordered by sender: grouping a speaker's lines
-- together measured 10% smaller than time order, because lz4 then sees the
-- repetition.
-- ---------------------------------------------------------------------------
-- Rollups. Nothing counts the raw log at read time.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS player_daily (
  day          DATE    NOT NULL,
  player_id    INTEGER NOT NULL,
  messages     INTEGER NOT NULL DEFAULT 0,
  deaths       INTEGER NOT NULL DEFAULT 0,
  pvp_deaths   INTEGER NOT NULL DEFAULT 0,
  kills        INTEGER NOT NULL DEFAULT 0,
  advancements INTEGER NOT NULL DEFAULT 0,
  joins        INTEGER NOT NULL DEFAULT 0,
  leaves       INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (day, player_id)
);

-- Added in r11. Playtime used to be a lead() over the whole event log at read
-- time, which is the one query that could not have survived archiving.
ALTER TABLE player_daily ADD COLUMN IF NOT EXISTS playtime_secs INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS player_daily_player_idx ON player_daily (player_id);

CREATE TABLE IF NOT EXISTS stats_daily (
  day      DATE   PRIMARY KEY,
  messages BIGINT NOT NULL DEFAULT 0,
  chat     BIGINT NOT NULL DEFAULT 0,
  joins    BIGINT NOT NULL DEFAULT 0,
  leaves   BIGINT NOT NULL DEFAULT 0,
  deaths   BIGINT NOT NULL DEFAULT 0,
  kills    BIGINT NOT NULL DEFAULT 0,
  goals    BIGINT NOT NULL DEFAULT 0
);

-- Recompute a closed date range from the raw log. Past days never change, so
-- the logger only ever refreshes today and yesterday.
CREATE OR REPLACE FUNCTION refresh_stats_daily(lo date, hi date)
RETURNS void LANGUAGE plpgsql AS $fn$
DECLARE lo_ts timestamptz; hi_ts timestamptz;
BEGIN
  lo_ts := lo::timestamp AT TIME ZONE 'UTC';
  hi_ts := (hi + 1)::timestamp AT TIME ZONE 'UTC';

  DELETE FROM stats_daily WHERE day >= lo AND day <= hi;

  INSERT INTO stats_daily (day, messages, chat, joins, leaves, deaths, kills, goals)
  SELECT day,
         sum(messages), sum(chat), sum(joins), sum(leaves),
         sum(deaths), sum(kills), sum(goals)
  FROM (
    SELECT (c.received_at AT TIME ZONE 'UTC')::date AS day,
           count(*)                                                         AS messages,
           count(*) FILTER (WHERE c.kind IN ('c', 'w'))                     AS chat,
           0::bigint AS joins, 0::bigint AS leaves,
           count(*) FILTER (WHERE c.kind = 'd')                             AS deaths,
           count(*) FILTER (WHERE c.kind = 'd' AND c.killer_id IS NOT NULL) AS kills,
           count(*) FILTER (WHERE c.kind = 'a')                             AS goals
    FROM chat_rows_between(lo_ts, hi_ts) c
    GROUP BY 1
    UNION ALL
    SELECT (e.occurred_at AT TIME ZONE 'UTC')::date,
           0, 0,
           count(*) FILTER (WHERE e.event_type = 'j'),
           count(*) FILTER (WHERE e.event_type = 'l'),
           0, 0, 0
    FROM event_rows_between(lo_ts, hi_ts) e
    GROUP BY 1
  ) parts
  GROUP BY day;
END;
$fn$;

CREATE OR REPLACE FUNCTION refresh_player_daily(lo date, hi date)
RETURNS void LANGUAGE plpgsql AS $fn$
DECLARE lo_ts timestamptz; hi_ts timestamptz;
BEGIN
  lo_ts := lo::timestamp AT TIME ZONE 'UTC';
  hi_ts := (hi + 1)::timestamp AT TIME ZONE 'UTC';

  DELETE FROM player_daily WHERE day >= lo AND day <= hi;

  INSERT INTO player_daily
    (day, player_id, messages, deaths, pvp_deaths, kills, advancements, joins, leaves, playtime_secs)
  SELECT day, player_id,
         sum(messages)::int, sum(deaths)::int, sum(pvp_deaths)::int, sum(kills)::int,
         sum(advancements)::int, sum(joins)::int, sum(leaves)::int, sum(playtime_secs)::int
  FROM (
    -- what a player said
    SELECT (c.received_at AT TIME ZONE 'UTC')::date AS day, c.sender_id AS player_id,
           count(*) AS messages, 0 AS deaths, 0 AS pvp_deaths, 0 AS kills,
           0 AS advancements, 0 AS joins, 0 AS leaves, 0 AS playtime_secs
    FROM chat_rows_between(lo_ts, hi_ts) c
    WHERE c.kind IN ('c', 'w') AND c.sender_id IS NOT NULL
    GROUP BY 1, 2

    UNION ALL
    -- what happened to a player
    SELECT (c.received_at AT TIME ZONE 'UTC')::date, c.subject_id,
           0,
           count(*) FILTER (WHERE c.kind = 'd'),
           count(*) FILTER (WHERE c.kind = 'd' AND kp.name_id IS NOT NULL),
           0,
           count(*) FILTER (WHERE c.kind = 'a'),
           0, 0, 0
    FROM chat_rows_between(lo_ts, hi_ts) c
    LEFT JOIN players kp ON kp.name_id = c.killer_id
    WHERE c.kind IN ('d', 'a') AND c.subject_id IS NOT NULL
    GROUP BY 1, 2

    UNION ALL
    -- kills, PvP only: the killer has to be a name we know as a real player
    SELECT (c.received_at AT TIME ZONE 'UTC')::date, c.killer_id,
           0, 0, 0, count(*), 0, 0, 0, 0
    FROM chat_rows_between(lo_ts, hi_ts) c
    JOIN players kp ON kp.name_id = c.killer_id
    WHERE c.kind = 'd' AND c.subject_id IS NOT NULL
    GROUP BY 1, 2

    UNION ALL
    -- comings and goings
    SELECT (e.occurred_at AT TIME ZONE 'UTC')::date, e.player_id,
           0, 0, 0, 0, 0,
           count(*) FILTER (WHERE e.event_type = 'j'),
           count(*) FILTER (WHERE e.event_type = 'l'),
           0
    FROM event_rows_between(lo_ts, hi_ts) e
    WHERE e.event_type IN ('j', 'l')
    GROUP BY 1, 2

    UNION ALL
    -- time in game, attributed to the day it was spent on rather than the day
    -- the session started, so a session across midnight lands on both.
    SELECT g.day, g.player_id, 0, 0, 0, 0, 0, 0, 0,
           EXTRACT(EPOCH FROM sum(
             least(spell.fin, (g.day + 1)::timestamp AT TIME ZONE 'UTC')
             - greatest(spell.beg, g.day::timestamp AT TIME ZONE 'UTC')))::int
    FROM (
      SELECT player_id,
             occurred_at AS beg,
             lead(occurred_at) OVER (PARTITION BY player_id ORDER BY occurred_at, id) AS fin,
             event_type,
             lead(event_type) OVER (PARTITION BY player_id ORDER BY occurred_at, id) AS fin_type
      -- One day either side, so a join just before the window and its leave
      -- just after both still bound the spell inside it.
      FROM event_rows_between(lo_ts - interval '1 day', hi_ts + interval '1 day')
      WHERE event_type IN ('j', 'l')
    ) spell
    CROSS JOIN LATERAL generate_series(
      greatest((spell.beg AT TIME ZONE 'UTC')::date, lo),
      least((spell.fin AT TIME ZONE 'UTC')::date, hi),
      interval '1 day') AS g_day(d)
    CROSS JOIN LATERAL (SELECT g_day.d::date AS day, spell.player_id) g
    WHERE spell.event_type = 'j' AND spell.fin_type = 'l' AND spell.fin > spell.beg
    GROUP BY g.day, g.player_id
  ) parts
  GROUP BY day, player_id;
END;
$fn$;

-- The shape the per-row triggers used to maintain, now a sum over one row per
-- day instead of an UPDATE that every insert in the database queued behind.
CREATE OR REPLACE VIEW logger_stats AS
  SELECT true AS id,
         COALESCE(sum(messages), 0)::bigint AS messages,
         COALESCE(sum(chat),     0)::bigint AS chat,
         COALESCE(sum(joins),    0)::bigint AS joins,
         COALESCE(sum(leaves),   0)::bigint AS leaves,
         COALESCE(sum(deaths),   0)::bigint AS deaths,
         COALESCE(sum(kills),    0)::bigint AS kills,
         COALESCE(sum(goals),    0)::bigint AS goals
  FROM stats_daily;

-- Kill/death tally per player, PvP only. Served from the rollup, so it no
-- longer scans every death line in history.
CREATE OR REPLACE VIEW kill_leaderboard AS
  SELECT nd.name,
         sum(d.kills)::bigint      AS kills,
         sum(d.pvp_deaths)::bigint AS deaths
  FROM player_daily d
  JOIN name_dict nd ON nd.id = d.player_id
  GROUP BY nd.name
  HAVING sum(d.kills) > 0 OR sum(d.pvp_deaths) > 0
  ORDER BY kills DESC, deaths ASC;

-- ---------------------------------------------------------------------------
-- Presence as state, not as a scan of the whole event log
-- ---------------------------------------------------------------------------

-- Two loggers can share one database (6b6t lobby + survival), so presence is
-- decided per session and only then unioned by name: a leave seen in the lobby
-- must not hide a player still on the survival tab list. Only sessions that are
-- still open count — a disconnect produces no RemovePlayer for everyone left on
-- the tab list, so closing the session retires those rows.
CREATE TABLE IF NOT EXISTS player_presence (
  session_id  INTEGER     NOT NULL,
  player_id   INTEGER     NOT NULL,
  server_host TEXT        NOT NULL,
  present     BOOLEAN     NOT NULL,
  at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (session_id, player_id)
);
CREATE INDEX IF NOT EXISTS player_presence_live_idx
  ON player_presence (server_host, player_id) WHERE present;

CREATE OR REPLACE VIEW online_now AS
  SELECT DISTINCT ON (pp.server_host, lower(nd.name))
         pp.server_host, nd.name AS player_name, p.uuid AS player_uuid, pp.at AS occurred_at
  FROM player_presence pp
  JOIN name_dict nd ON nd.id = pp.player_id
  JOIN sessions s ON s.id = pp.session_id AND s.ended_at IS NULL
  LEFT JOIN players p ON p.name_id = pp.player_id
  WHERE pp.present
  ORDER BY pp.server_host, lower(nd.name), pp.at DESC;

-- ---------------------------------------------------------------------------
-- Columnar archival for closed days
-- ---------------------------------------------------------------------------
-- Everything else, unchanged
-- ---------------------------------------------------------------------------

-- How long sessions actually last, per server. This is the number that showed
-- mineflayer capping out at ~35s on Constantiam.
CREATE OR REPLACE VIEW session_stats AS
  SELECT server_host,
         client,
         count(*)                                                            AS sessions,
         round(avg(EXTRACT(EPOCH FROM (ended_at - started_at)))::numeric, 1) AS avg_secs,
         round(max(EXTRACT(EPOCH FROM (ended_at - started_at)))::numeric, 1) AS max_secs
  FROM sessions
  WHERE ended_at IS NOT NULL
  GROUP BY server_host, client;

-- In-game plugin probe results (command tree / tab-complete / chat), one row
-- per scan. The Discord bot reads the newest row per database.
CREATE TABLE IF NOT EXISTS server_plugin_scans (
  id           BIGSERIAL PRIMARY KEY,
  session_id   BIGINT REFERENCES sessions (id) ON DELETE CASCADE,
  server_host  TEXT        NOT NULL,
  scanned_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  server_brand TEXT,
  methods      TEXT[]      NOT NULL DEFAULT '{}',
  plugins      JSONB       NOT NULL DEFAULT '[]',
  raw_notes    TEXT
);

CREATE INDEX IF NOT EXISTS plugin_scans_host_idx ON server_plugin_scans (server_host, scanned_at DESC);

-- Live 2b2t-style queue probe (QUEUE_PROBE=true logger). Single row + history.
CREATE TABLE IF NOT EXISTS queue_status (
  id         BOOLEAN PRIMARY KEY DEFAULT true,
  position   INTEGER,
  raw_text   TEXT,
  in_queue   BOOLEAN     NOT NULL DEFAULT false,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT queue_status_one_row CHECK (id)
);

CREATE TABLE IF NOT EXISTS queue_samples (
  id          BIGSERIAL PRIMARY KEY,
  position    INTEGER     NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS queue_samples_recorded_idx ON queue_samples (recorded_at DESC);

-- Server-seeker discoveries live in tools/server-seeker/schema.sql (discovered_servers).
-- Apply that file to the SEEKER_DATABASE_URL database used by mc-discord-bot.

-- Standby loggers. Every logger upserts its own row every HEARTBEAT_SECS; a
-- standby writes nothing while a *primary* row for the same host is both
-- connected and fresh. Presence alone cannot be inferred from recent writes:
-- a quiet server looks identical to a dead logger, and the standby would take
-- over and duplicate every row once the primary came back.
CREATE TABLE IF NOT EXISTS logger_heartbeats (
  instance     TEXT PRIMARY KEY,
  role         TEXT        NOT NULL DEFAULT 'primary',
  server_host  TEXT        NOT NULL,
  session_id   BIGINT,
  bot_username TEXT,
  connected    BOOLEAN     NOT NULL DEFAULT false,
  writing      BOOLEAN     NOT NULL DEFAULT false,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS logger_heartbeats_host_idx
  ON logger_heartbeats (server_host, role, updated_at DESC);

-- The server's own player count, parsed straight from its tab-list header
-- ("Online players: 504", "587 players online") — a number the server
-- already maintains and broadcasts on its own, independent of and much
-- faster than the PlayerInfoUpdate roster this database otherwise has to
-- reconstruct player-by-player. Written whenever it changes, not on a timer.
ALTER TABLE logger_heartbeats ADD COLUMN IF NOT EXISTS reported_online INTEGER;
ALTER TABLE logger_heartbeats ADD COLUMN IF NOT EXISTS reported_online_at TIMESTAMPTZ;
